# Python Package
#
# Automatically build and test the package for supported Python 3.x versions.
#

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python: [3.6, 3.7]
    name: Python ${{ matrix.python }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: ${{ matrix.python }}
          conda-channels: pytorch
      - name: Install Dependencies
        run: |
          source activate base
          conda install pytorch torchvision cpuonly -c pytorch
          conda install poetry invoke
          poetry install
          which python
          which poetry
          which invoke
      - name: Check PyTorch
        run: |
          /usr/share/miniconda/bin/python -c "import torch; print(torch.__version__)"
          python -c "import torch; print(torch.__version__)"
      - name: Run Automated Tests
        run: |
          /usr/share/miniconda/bin/python -m poetry run pytest -c tasks/pytest.ini -k test_
      - name: Run Application Tests
        run: |
          /usr/share/miniconda/bin/python -m poetry run pytest -c tasks/pytest.ini -k app_
      - name: Create Package
        run: |
          poetry build
